#apps are located in
#/var/www/apps inside container
test81.com:
  documentRoot: /var/www/apps/test
  version: "8.1"
  enabled: 1

test74.com:
  documentRoot: /var/www/apps/test
  version: "7.4"
  enabled: 1

test73.com:
  documentRoot: /var/www/apps/test
  version: "7.3"
  enabled: 1

test72.com:
  documentRoot: /var/www/apps/test
  version: "7.2"
  enabled: 1

test7.com:
  documentRoot: /var/www/apps/test
  version: "7"
  enabled: 1

test56.com:
  documentRoot: /var/www/apps/test
  version: "5.6"
  enabled: 1
#  authFile: /var/www/apps/test/.htpasswd
